nineOne:
  re:
    indexVideoUrlList: videos-text-align
    directUrlEscape: strencode2\((.*?)\)\)
    m3u8Url: src='(.*?)'
  url:
    detail: https://91porn.com/view_video.php?viewkey=
    # 最新视频
    theLatest: https://91porn.com/v.php?page=
    # 今日排行
    todayRank: https://91porn.com/index.php
    # 当前最热
    nowHot: https://91porn.com/v.php?category=hot&viewtype=basic&page=
    # 本月最热
    thisMonthHot: https://91porn.com/v.php?category=top&viewtype=basic&page=
    # 上月最热
    lastMonthHot: https://91porn.com/v.php?category=top&m=-1&viewtype=basic&page=
    # 本月收藏
    thisMonthCollect: https://91porn.com/v.php?category=tf&viewtype=basic&page=
    # 收藏最多
    allTimeCollect: https://91porn.com/v.php?category=mf&viewtype=basic&page=
    # 最近加精
    recentRefined: https://91porn.com/v.php?category=rf&viewtype=basic&page=

http:
  proxy:
    host: 127.0.0.1
    port: 1087

logging:
  level:
    root: INFO

spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto-hotswapping.html
  thymeleaf:
    cache: false
  security:
    user:
      name: avhub
      password: fuckCar
  datasource:
    url: jdbc:h2:file:./data/avhub
    driver-class-name: org.h2.Driver
    username: root
    password: 1234
    data:
      - classpath:/sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update